backend:
  name: git-gateway
  branch: master

locale: "es"

site_url: https://codingdojo-test.netlify.app/

media_folder: static/assets/
public_folder: /assets

collections:
  - name: language
    identifier_field: name
    label: Lenguaje de programación
    folder: content/languages
    create: true

    fields:
      - name: name
        label: Nombre del lenguaje/tecnología
        widget: string

      - name: whatis
        label: ¿Qué es el lenguaje?
        widget: text
        hint: Un texto descriptivo que responda a la pregunta, por ejemplo ¿Qué es Python?

      - name: languageImg
        label: Imagen del lenguaje
        hint: Esto es el logo del lenguaje, alrededor de un 160x160
        widget: image

      - name: featuredImg
        label: Imagen de portada
        hint: Tiene que tener un ancho de 1920 píxeles
        widget: image

      - name: technologies
        label: Tecnologías
        widget: list
        fields:
          - name: name
            label: Nombre
            widget: string
          - name: icon
            label: Ícono
            widget: image
            allow_multiple: false

      - name: companies
        label: Compañías
        hint: Subir fotos de los logos de las compañías que usan este lenguaje (idealmente logos horizontales)
        widget: list
        max: 6
        field: { name: imagen, label: Imagen, widget: image }

      - name: commonUseCases
        label: Usos comunes
        hint: Insertar imagen y texto de los usos comunes del lenguaje
        widget: list
        fields:
          - name: title
            label: Título
            widget: string
          - name: image
            label: Imagen
            widget: image

      - name: features
        label: Características
        hint: Insertar imagen y texto de las características del lenguaje
        widget: list
        fields:
          - name: title
            label: Título
            widget: string
          - name: description
            label: Descripción
            widget: text
          - name: image
            label: Imagen
            widget: image

      - name: bottomImage
        label: Imagen inferior
        hint: Imagen que se adjuntará después de la sección de características
        widget: image

      - name: topics
        label: Temas abordados
        hint: Una lista de cada tema que se aborda en el curso
        widget: list
